repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: pretty-format-json
        args:
          - '--autofix'
          - '--no-sort-keys'
      - id: detect-private-key