---

- hosts: all
  become: yes
  user: <user>
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repositorio'
    raw: 'apt-get update'
  - name: 'Instalando o Python'
    raw: 'apt-get install -y python'
  roles:
  - { role: install_iptables , tags: ["install_iptables_role"] }

- hosts: all
  become: yes
  user: <user>
  roles:
  - { role: limpando_regras, tags: ["limpando_regras_role"]}

- hosts: webservers
  become: yes
  user: <user>
  roles:
  - { role: webserver_ports, tags: ["webserver_ports_role"] }

- hosts: all
  become: yes
  user: <user>
  roles:
  - { role: regras_default, tags: ["regras_default_role"] }

- hosts: all
  become: yes
  user: <user>
  roles:
  - { role: save_rules, tags: ["save_rules_role"] }

