---

- name: Permitindo trafego porta 80/HTTP
  iptables:
    chain: INPUT
    destination_port: "80"
    jump: ACCEPT
    protocol: tcp

- name: Permitindo trafego porta 443/HTTPS
  iptables:
    chain: INPUT
    destination_port: "443"
    jump: ACCEPT
    protocol: tcp